// Generated by oss-cad-suite's gowin_pll:
//
//   gowin_pll -d "GW2A-18 C8/I7" -i 27 -o 14.7456 -m SysPll -f pll.sv
//
// 14.7456 MHz was asked for because it divides exactly to 115200 baud; the
// PLL cannot hit it from 27 MHz and lands on 15 MHz, which is what the rest
// of the port is built around. 15 MHz also divides exactly to the 1 MHz mtime
// timebase, and leaves 21% margin against the 19 MHz the core closes at.
//
// The original header follows.
//
/**
 * PLL configuration
 *
 * This Verilog module was generated automatically
 * using the gowin-pll tool.
 * Use at your own risk.
 *
 * Target-Device:                GW2A-18 C8/I7
 * Given input frequency:        27.000 MHz
 * Requested output frequency:   14.746 MHz
 * Achieved output frequency:    15.000 MHz
 */

module SysPll(
        input  clock_in,
        output clock_out,
        output locked
    );

    rPLL #(
        .FCLKIN("27.0"),
        .IDIV_SEL(8), // -> PFD = 3.0 MHz (range: 3-500 MHz)
        .FBDIV_SEL(4), // -> CLKOUT = 15.0 MHz (range: 3.90625-625 MHz)
        .ODIV_SEL(48) // -> VCO = 720.0 MHz (range: 500-1250 MHz)
    ) pll (.CLKOUTP(), .CLKOUTD(), .CLKOUTD3(), .RESET(1'b0), .RESET_P(1'b0), .CLKFB(1'b0), .FBDSEL(6'b0), .IDSEL(6'b0), .ODSEL(6'b0), .PSDA(4'b0), .DUTYDA(4'b0), .FDLY(4'b0), 
        .CLKIN(clock_in), // 27.0 MHz
        .CLKOUT(clock_out), // 15.0 MHz
        .LOCK(locked)
    );

endmodule
