#!/usr/bin/env bash
# Build the CPU-controlled LCD system in the pinned FPGA container.
set -euo pipefail
root="$(cd "$(dirname "$0")/.." && pwd)"
cd "$root"
suite="${OSS_CAD_SUITE:-}"
if [[ -z "$suite" ]]; then
    for candidate in /opt/oss-cad-suite "$HOME/toolchain/oss-cad-suite"; do
        if [[ -x "$candidate/bin/yosys" ]]; then suite="$candidate"; break; fi
    done
fi
if [[ ! -x "$suite/bin/yosys" ]]; then
    echo 'Set OSS_CAD_SUITE to the pinned OSS CAD Suite directory' >&2
    exit 1
fi
export PATH="$suite/bin:$PATH"
out=sim/fpga/lcd_soc
mkdir -p "$out"
veryl build > "$out/veryl.log" 2>&1
scripts/build_fw.sh
rtl=(target/rv_pkg.sv target/alu.sv target/core.sv target/clint.sv
     target/plic.sv target/soc.sv target/uart.sv target/ram.sv target/fpga_soc.sv)
# All inputs are generated by Veryl. The primitive wrapper uses read_verilog
# because read_slang cannot override parameters of the opaque device rPLL.
yosys -m slang -p "
    read_slang --top rv32ima_TangLcdSystem ${rtl[*]} target/tang_primer_20k/lcd_timing.sv target/tang_primer_20k/lcd_mmio.sv target/tang_primer_20k/lcd_system.sv
    read_slang --top rv32ima_PowerOnReset target/power_on_reset.sv
    read_verilog -sv target/tang_primer_20k/lcd_clock.sv target/tang_primer_20k/lcd_soc.sv
    synth_gowin -top rv32ima_TangLcdSoc -json $out/soc.json
" > "$out/yosys.log" 2>&1 || { tail -30 "$out/yosys.log" >&2; exit 1; }
# Reuse the verified LCD pin map, adding the core-board UART pair.
cat fpga/tang_primer_20k/lcd_probe.cst fpga/tang_primer_20k/lcd_soc_uart.cst > "$out/soc.cst"
nextpnr-himbaechel --device GW2A-LV18PG256C8/I7 --vopt family=GW2A-18C \
    --vopt "cst=$out/soc.cst" --pre-pack fpga/tang_primer_20k/lcd_soc_clocks.py \
    --json "$out/soc.json" --write "$out/soc-pnr.json" --freq 27 --report "$out/timing.json" \
    > "$out/nextpnr.log" 2>&1 || { tail -30 "$out/nextpnr.log" >&2; exit 1; }
gowin_pack -d GW2A-18C -o "$out/soc.fs" "$out/soc-pnr.json" > "$out/pack.log" 2>&1
echo "LCD SoC: $out/soc.fs"
